[profile.default]
optimizer=false
evm_version = 'shanghai'
src = 'src'
out = 'out'
libs = ['lib']
remappings = [    
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config